import { Document, Paragraph, TextRun, HeadingLevel, AlignmentType, Packer } from 'docx';

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

export async function generateWordDocument(
  messages: ChatMessage[],
  title: string = 'AIDOMO Chat Export'
): Promise<Buffer> {
  try {
    // Create document sections
    const sections: Paragraph[] = [];

    // Add title
    sections.push(
      new Paragraph({
        text: title,
        heading: HeadingLevel.HEADING_1,
        alignment: AlignmentType.CENTER,
        spacing: {
          after: 400,
        },
      })
    );

    // Add export info
    const exportDate = new Date().toLocaleString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });

    sections.push(
      new Paragraph({
        text: `Exported from AIChecklist.io on ${exportDate}`,
        alignment: AlignmentType.CENTER,
        italics: true,
        spacing: {
          after: 600,
        },
      })
    );

    // Add each message
    messages.forEach((message, index) => {
      // Add message header
      sections.push(
        new Paragraph({
          children: [
            new TextRun({
              text: message.role === 'user' ? '👤 You' : '🤖 AIDOMO',
              bold: true,
              size: 28,
              color: message.role === 'user' ? '2563eb' : '16a34a',
            }),
          ],
          spacing: {
            before: index === 0 ? 0 : 400,
            after: 200,
          },
        })
      );

      // Split content into paragraphs (by newlines)
      const contentParagraphs = message.content.split('\n').filter(p => p.trim());

      contentParagraphs.forEach(paragraph => {
        sections.push(
          new Paragraph({
            text: paragraph,
            spacing: {
              after: 120,
            },
          })
        );
      });

      // Add separator line
      if (index < messages.length - 1) {
        sections.push(
          new Paragraph({
            text: '─'.repeat(80),
            alignment: AlignmentType.CENTER,
            spacing: {
              before: 300,
              after: 300,
            },
          })
        );
      }
    });

    // Add footer
    sections.push(
      new Paragraph({
        text: '',
        spacing: {
          before: 600,
        },
      })
    );

    sections.push(
      new Paragraph({
        text: 'Generated by AIChecklist.io - Your AI-Powered Task Management Platform',
        alignment: AlignmentType.CENTER,
        italics: true,
        color: '6b7280',
      })
    );

    // Create the document
    const doc = new Document({
      sections: [
        {
          properties: {},
          children: sections,
        },
      ],
    });

    // Generate buffer
    const buffer = await Packer.toBuffer(doc);
    return buffer;
  } catch (error) {
    console.error('Error generating Word document:', error);
    throw new Error('Failed to generate Word document');
  }
}
